preferred_syntax = :sass
http_path = '/'
css_dir = 'public/css'
sass_dir = 'public/scss'
images_dir = 'public/images'
javascripts_dir = 'public/js'
relative_assets = true
line_comments = true
# output_style = :compressed